"""empty message

Revision ID: 92142f46cb5b
Revises: 18ccea3442ae
Create Date: 2024-11-24 03:05:35.370311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92142f46cb5b'
down_revision = '18ccea3442ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['planet_id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['character_id'])
        batch_op.drop_column('favorite_type')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('favorite_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
